# Generated by Django 4.2.14 on 2024-08-03 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplication', '0003_alter_baseball_a_bb_alter_baseball_a_ma_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultado_NLF_profecional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('ganador', models.CharField(default='Empate', max_length=100, verbose_name='Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplication.nlf_profecional', verbose_name='Partido')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_NLF_colegial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('ganador', models.CharField(default='Empate', max_length=100, verbose_name='Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplication.nlf_colegial', verbose_name='Partido')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_NBA_profecional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('ganador', models.CharField(default='Empate', max_length=100, verbose_name='Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplication.nba_profecional', verbose_name='Partido')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_NBA_colegial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('ganador', models.CharField(default='Empate', max_length=100, verbose_name='Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplication.nba_colegial', verbose_name='Partido')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_Hockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('ganador', models.CharField(default='Empate', max_length=100, verbose_name='Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplication.hockey', verbose_name='Partido')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('ganador', models.CharField(default='Empate', max_length=100, verbose_name='Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplication.futbol', verbose_name='Partido')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_baseball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('ganador', models.CharField(default='Empate', max_length=100, verbose_name='Ganador')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplication.baseball', verbose_name='Partido')),
            ],
        ),
    ]
