# Generated by Django 4.2.14 on 2024-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos_nba_profecional',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
