# Generated by Django 4.2.14 on 2024-07-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseball',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_baseballs', to='equipos.equipos_baseball', verbose_name='Home'),
        ),
        migrations.AlterField(
            model_name='baseball',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante_baseballs', to='equipos.equipos_baseball', verbose_name='Away'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_futbols', to='equipos.equipos_futbol', verbose_name='Home'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante_futbols', to='equipos.equipos_futbol', verbose_name='Away'),
        ),
    ]
