# Generated by Django 4.2.14 on 2024-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_futbol_ganador_futbol_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbol',
            name='ganador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ganador'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado'),
        ),
    ]
