# Generated by Django 4.2.14 on 2024-08-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0005_alter_futbol_ganador_alter_futbol_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hockey',
            name='J_BB',
        ),
    ]
