# Generated by Django 4.2.14 on 2024-08-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_remove_hockey_j_bb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futbol',
            name='A_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='A_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='A_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='A_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='A_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='A_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='B_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='B_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='B_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='B_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='B_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='B_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='C_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='C_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='C_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='C_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='C_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='C_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='D_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='D_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='D_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='D_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='D_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='D_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='E_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='E_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='E_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='E_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='E_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='E_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='F_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='F_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='F_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='F_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='F_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='F_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='G_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='G_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='G_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='G_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='G_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='G_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='H_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='H_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='H_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='H_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='H_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='H_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='I_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='I_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='I_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='I_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='I_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='I_Ud',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='J_ML',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='J_O',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='J_SB',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='J_SP',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='J_U',
        ),
        migrations.RemoveField(
            model_name='futbol',
            name='J_Ud',
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='A_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_ML_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneline Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_SB_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_SP_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spread Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_Ud_equip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Underdogs Equipo'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_BB',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_MA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Money Adventaje Equipo'),
        ),
    ]
