# Generated by Django 4.2.14 on 2024-08-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0007_remove_futbol_a_ml_remove_futbol_a_o_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futbol',
            name='A_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='B_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='C_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='D_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='E_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='F_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='G_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='H_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='I_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
        migrations.AddField(
            model_name='futbol',
            name='J_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia'),
        ),
    ]
