# Generated by Django 4.2.14 on 2024-08-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipos_nba_profecional_logo'),
        ('aplication', '0008_futbol_a_total_punto_futbol_b_total_punto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbol',
            name='A_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_A', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_A', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_A', to='equipos.equipos_futbol', verbose_name='Moneline Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_A', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_A', to='equipos.equipos_futbol', verbose_name='Spread Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_A', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_B', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_B', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_B', to='equipos.equipos_futbol', verbose_name='Moneline Equipo1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_B', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Sharp Bettors Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Diferencia1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_B', to='equipos.equipos_futbol', verbose_name='Spread Equipo1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Spread Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_Total_OU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total: Over/Under1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Total Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_B', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Underdogs Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Referencia1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_C', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_C', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_C', to='equipos.equipos_futbol', verbose_name='Moneline Equipo2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Moneline Probabilidad2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_C', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_C', to='equipos.equipos_futbol', verbose_name='Spread Equipo2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_C', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_D', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_D', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo3'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_D', to='equipos.equipos_futbol', verbose_name='Moneline Equipo3'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_D', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo3'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_D', to='equipos.equipos_futbol', verbose_name='Spread Equipo3'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_D', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo3'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_E', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo4'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_E', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo4'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_E', to='equipos.equipos_futbol', verbose_name='Moneline Equipo4'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_E', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo4'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_E', to='equipos.equipos_futbol', verbose_name='Spread Equipo4'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_E', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo4'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_F', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo5'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_F', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo5'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_F', to='equipos.equipos_futbol', verbose_name='Moneline Equipo5'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_F', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo5'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_F', to='equipos.equipos_futbol', verbose_name='Spread Equipo5'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_F', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo5'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_G', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo6'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_G', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo6'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_G', to='equipos.equipos_futbol', verbose_name='Moneline Equipo6'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_G', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo6'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_G', to='equipos.equipos_futbol', verbose_name='Spread Equipo6'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_G', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo6'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_H', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo7'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_H', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo7'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_H', to='equipos.equipos_futbol', verbose_name='Moneline Equipo7'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_H', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo7'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_H', to='equipos.equipos_futbol', verbose_name='Spread Equipo7'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_H', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo7'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_I', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo8'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_I', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo8'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_I', to='equipos.equipos_futbol', verbose_name='Moneline Equipo8'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_I', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo8'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_I', to='equipos.equipos_futbol', verbose_name='Spread Equipo8'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_I', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo8'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_BB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Best_Bets_J', to='equipos.equipos_futbol', verbose_name='Best Bets Equipo9'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_MA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Money_Adventaje_J', to='equipos.equipos_futbol', verbose_name='Money Adventaje Equipo9'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_ML_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Moneline_J', to='equipos.equipos_futbol', verbose_name='Moneline Equipo9'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_SB_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sharp_Bettors_J', to='equipos.equipos_futbol', verbose_name='Sharp Bettors Equipo9'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_SP_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Spread_J', to='equipos.equipos_futbol', verbose_name='Spread Equipo9'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_Ud_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Underdogs_J', to='equipos.equipos_futbol', verbose_name='Underdogs Equipo9'),
        ),
    ]
