# Generated by Django 4.2.14 on 2024-08-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0010_remove_baseball_a_ml_remove_baseball_a_o_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbol',
            name='A_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='A_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_ML_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Moneline Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_SB_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Sharp Bettors Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_SP_dif',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Diferencia'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_SP_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Spread Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_Total_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Total Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_Ud_prob',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Underdogs Probabilidad'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_total_punto',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Referencia'),
        ),
    ]
