# Generated by Django 4.2.14 on 2024-08-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_total'),
        ('aplication', '0012_futbol_a_bb_prob_futbol_a_ma_prob_futbol_b_bb_prob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futbol',
            name='A_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal1', to='equipos.total', verbose_name='Total: Over/Under'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='B_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal2', to='equipos.total', verbose_name='Total: Over/Under1'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='C_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal3', to='equipos.total', verbose_name='Total: Over/Under2'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='D_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal4', to='equipos.total', verbose_name='Total: Over/Under3'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='E_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal5', to='equipos.total', verbose_name='Total: Over/Under4'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='F_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal6', to='equipos.total', verbose_name='Total: Over/Under5'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='G_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal7', to='equipos.total', verbose_name='Total: Over/Under6'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='H_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal8', to='equipos.total', verbose_name='Total: Over/Under7'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='I_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal9', to='equipos.total', verbose_name='Total: Over/Under8'),
        ),
        migrations.AlterField(
            model_name='futbol',
            name='J_Total_OU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='futboltotal10', to='equipos.total', verbose_name='Total: Over/Under9'),
        ),
    ]
